---
title: "SchirmacherAyden_FinalProject"
output:
  html_document:
    df_print: paged
date: "`r Sys.Date()`"
---
##Data Wrangling
```{r clear environment, include=FALSE, warning=FALSE, message=FALSE}
remove(list=ls())
```

```{r packages, warning=FALSE, message=FALSE, include=FALSE}
#install.packages("dplyr")
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("ggrepel")
#install.packages("here")
#install.packages("gifski")
#install.packages("gganimate")
#install.packages("gapminder")
#install.packages("scales")
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggrepel)
library(here)
library(gifski)
library(gganimate)
library(gapminder)
library(scales)
```

```{r data import, message=FALSE, warning=FALSE, include=FALSE}
getwd()

fish_2022<-read.csv(here("Data", "Raw", "2022.csv"))
fish_2021<-read.csv(here("Data", "Raw", "2021.csv"))
fish_2020<-read.csv(here("Data", "Raw", "2020.csv"))
fish_2019<-read.csv(here("Data", "Raw", "2019.csv"))
fish_2018<-read.csv(here("Data", "Raw", "2018.csv"))
fish_2017<-read.csv(here("Data", "Raw", "2017.csv"))
fish_2016<-read.csv(here("Data", "Raw", "2016.csv"))
fish_2015<-read.csv(here("Data", "Raw", "2015.csv"))
fish_2014<-read.csv(here("Data", "Raw", "2014.csv"))

fish_all <- bind_rows(
  "2014" = fish_2014, 
  "2015" = fish_2015, 
  "2016" = fish_2016, 
  "2017" = fish_2017, 
  "2018" = fish_2018, 
  "2019" = fish_2019, 
  "2020" = fish_2020, 
  "2021" = fish_2021, 
  "2022" = fish_2022, 
  .id = "Year")
```

```{r cleaning the data, message=FALSE, warning=FALSE, include=FALSE}

fish_all$FINALWEIGHT <- gsub("[,]", "", fish_all$FINALWEIGHT) 
#^^remove commas from data
fish_all$FINALVALUE <- gsub("[,]", "", fish_all$FINALVALUE)
#^^remove commas from data
fish_all$FINALVALUE <- gsub("\\$", "", fish_all$FINALVALUE)
#^^remove dollar signs from data

fish_all<-fish_all%>%
  filter(!is.na(FINALWEIGHT))%>% #filter for NA
  filter(!is.na(FINALVALUE))%>% #filter for NA
  mutate(FINALWEIGHT=as.integer(FINALWEIGHT))%>% #make data into numerical
  mutate(FINALVALUE=as.integer(FINALVALUE))%>% #make data into numerical
 mutate(Year = as.Date(paste0(Year, "-01-01"), format="%Y-%m-%d")) 
#^^create date object

#Keeping only the fish observations that are present across all years
fish_all<-fish_all %>%
  select(Year, FISH, FINALWEIGHT, FINALVALUE)%>%
  group_by(FISH) %>%
  filter(n_distinct(Year) == length(unique(fish_all$Year))) %>%
  #^^keep only the observations across all years
  ungroup()
```

```{r group by species type, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)

fish_all <- fish_all %>%
  mutate(species_group = case_when(
    FISH %in% c("Blue Crabs, Hard", "Blue Crabs, Peeler", 
                "Blue Crabs, Soft", 
                "Stone Crabs") 
    ~ "Crab",
    
    FISH %in% c("Shrimp (Heads On)")
    ~ "Shrimp",
    
    FISH %in% c("Clams, Hard (Meats)", "Clams, Hard (Numbers)", 
                "Oysters (Bushels)", "Oysters (Meats)", 
                "Scallop, Sea (Meats)", "Squid", 
                "Whelks/Conchs (Meats)", "Octopus") 
    ~ "Mollusks",

    FISH %in% c("Dogfish, Smooth", "Dogfish, Spiny", 
                "Sharks", "Skates") 
    ~ "Sharks & Rays",

    FISH %in% c("Eel, American") ~ "Eels",

    FISH %in% c("Flounder, Southern", "Flounder, Summer", 
                "Flounders, Other") 
    ~ "Flatfish",

    FISH %in% c("Croaker, Atlantic", "Drum, Black", "Drum, Red", 
                "Seatrout, Spotted", "Weakfish (Grey Trout)", 
                "Spot") 
    ~ "Drum & Croaker Family",

    FISH %in% c("Grouper, Gag", "Grouper, Red", "Grouper, Scamp", 
                "Grouper, Snowy", "Groupers, Other", "Sea Basses") 
    ~ "Groupers & Sea Basses",

    FISH %in% c("Snapper, Vermilion (Beeliner)", 
                "Snappers, Other", "Porgies") 
    ~ "Snappers & Porgies",

    FISH %in% c("Mackerel, Atlantic (Boston)", "Mackerel, King", 
                "Mackerel, Spanish", "Tuna, Bigeye", "Tuna, Bluefin",
                "Tuna, Yellowfin", "Tunas, Other", 
                "Tunny, Little (False Albacore)") ~ "Mackerels & Tunas",

    FISH %in% c("Amberjacks", 
                "Jacks (Crevalle, Rainbowrunner, Bluerunner)", "Pompano") 
    ~ "Jacks & Pompanos",

    FISH %in% c("Anglerfish (Monkfish Including Monklivers)", "Bluefish", "Bonito", 
                "Butterfish", "Carp", "Catfishes", "Cobia", "Cutlassfish, Atlantic", 
                "Dolphinfish", "Garfish", "Grunts", "Hakes", "Harvestfish (Starbutters)", 
                "Hogfish (Hog Snapper)", "Mullet, Sea (Kingfishes)", "Mullet, Striped", 
                "Perch, White", "Perch, Yellow", "Pigfish", "Pinfish", "Pufferfish", 
                "Scup", "Shad, American", "Shad, Gizzard", "Shad, Hickory", "Sheepshead", 
                "Skippers", "Spadefish", "Striped Bass", "Swordfish", "Tilefish, Blueline", 
                "Tilefish, Other", "Triggerfish", "Wahoo") ~ "Other Finfish",
    FISH %in% c("Unclassified Fish For Industrial/Bait", "Unclassified Fish for Food", 
                "Unclassified Shellfish") ~ "Unclassified",
    TRUE ~ "Other"
  ))

```

```{r new value to weight ratio, message=FALSE, warning=FALSE, include=FALSE}
fish_all<-fish_all%>%
  mutate(value_weight_ratio=FINALVALUE/FINALWEIGHT)
```

```{r create difference in means between 1972 and 2022, message=FALSE, warning=FALSE, include=FALSE}
fish_year01<-fish_all%>%
  filter(Year=="2014-01-01")
fish_year50<-fish_all%>%
  filter(Year=="2022-01-01")

fish_diff<- 
  left_join(fish_year50, fish_year01, by = "FISH", suffix = c("_2022", "_2014")) %>%
  mutate(diff_means = value_weight_ratio_2022 - value_weight_ratio_2014)

fish_all <- left_join(fish_all, fish_diff %>% select(FISH, diff_means), by = "FISH")

```


##Exploratory Plots
```{r value by year plot, message=FALSE, warning=TRUE, echo=FALSE}
year_value_plot<-
  ggplot(fish_all, aes(x = Year, y = FINALVALUE, col=species_group))+
  geom_point(alpha = 0.40)+
  labs(
    title="Final Value from Commercial Fishing by Species Type
    in North Carolina, 2014-2022",
    x="Year", y="Value ($USD)")+
  theme_bw()

year_value_plot
```

```{r weight by year plot, message=FALSE, warning=FALSE, echo=FALSE}
year_weight_plot<-
  ggplot(fish_all, aes(x = Year, y = FINALWEIGHT, col=species_group))+
  geom_point(alpha = 0.40)+
  labs(
    title="Final Weight from Commercial Fishing by Species Type
    in North Carolina, 2014-2022",
    x="Year", y="Weight (units)")+
  theme_bw()

year_weight_plot
```

```{r log plot value by species group, warning=FALSE, message=FALSE, echo=FALSE}
ggplot(fish_all, aes(x = Year, y = FINALVALUE, col = species_group))+
  geom_point()+
  scale_y_log10()+
  geom_smooth(method = lm, color="red", linewidth=0.45)+
  labs(x="Year", y="Value ($USD)", 
  title = "Final Value from Commercial Fishing
          by Species Type in North Carolina, 2014-2022")+
  facet_wrap(~ species_group)
```

```{r ratio plot, warning=FALSE, message=FALSE, echo=FALSE}
fish_plot<-
  ggplot(fish_all, aes(x = FINALWEIGHT, y = FINALVALUE, col=species_group))+
  geom_point(alpha = 0.40)+
  labs(
    title="Ratio of Fish Weight to Value from Commercial Fishing
    by Species Type in North Carolina, 2014-2022",
    x="Weight (Units)", y="Value ($USD)")+
  scale_y_continuous(labels=comma)+
  scale_x_continuous(labels=comma)+
  geom_text_repel(data = fish_all%>%
                  filter(abs(FINALVALUE) > 23000000),
                  aes(label = paste(FISH, format(Year, "%Y"))),
                  color = 'red', size=3)+
  theme_bw()

fish_plot
```

```{r log ratio plot, warning=FALSE, message=FALSE, echo=FALSE}
fish_log_plot<-
  ggplot(fish_all, aes(x = FINALWEIGHT, y = FINALVALUE, col=species_group))+
  scale_x_log10()+
  scale_y_log10()+
  geom_point(alpha = 0.40)+
  geom_text_repel(data = fish_all%>%
                  filter(abs(FINALVALUE) > 23000000),
                  aes(label = paste(FISH, format(Year, "%Y"))),
                  color = 'red', size=3)+
  ggtitle("Logged Ratio of Fish Weight to Value from Commercial Fishing
          by Species Type in North Carolina, 2014-2022")+
  xlab("Log Scale Weight (Units)")+
  ylab("Value ($USD)")+
  theme_bw()

fish_log_plot
```

```{r animation over time, warning=FALSE, message=FALSE, echo=FALSE}
#this animation plot can't be knitted to a PDF file
fish_animate<-
  ggplot(fish_all, aes(x = FINALWEIGHT, y = FINALVALUE, 
                       size=3,
                       col = FISH)) +
    geom_point(alpha = 0.7, show.legend = FALSE) +
    scale_x_log10()+
    labs(title = 'Ratio of Value to Log Weight, Year: {closest_state}', 
       x = 'Log Scale Weight (Units)', 
       y = 'Value ($USD)') +
    transition_states(Year, transition_length = 1, state_length = 1,
                      wrap = TRUE)+
    ease_aes('cubic-in-out')+
  geom_text(data = fish_all%>%
    filter(FINALVALUE > 6000000),
    aes(label=FISH), 
    hjust = 1, vjust = 0, size = 3, color = "black")

animate(fish_animate, fps = 30, duration = 15)
```

##Statistical Analysis

**Two sample t-test for value-to-weight ratio 1972 vs. 2022**
```{r two sample t test between year 01 and year 50, message=FALSE, warning=FALSE, echo=FALSE}

t_test_results <- fish_all %>%
  group_by(species_group) %>%
  summarise(p_value = t.test(
    value_weight_ratio[Year == "2014-01-01"], 
    value_weight_ratio[Year == "2022-01-01"], 
    alternative = "two.sided", 
    var.equal = FALSE
  )$p.value)

print(t_test_results)

#two sample t-test with the output showing the p-values... species groups with 
#significant p-values have a significant change between 1972 and 2022 in the
#value to weight ratio. 

```

**ANOVA test across all years**
```{r ANOVA, message=FALSE, warning=FALSE, echo=FALSE}
fish_anova<-aov(data=fish_all, FINALVALUE ~ FINALWEIGHT) 

summary(fish_anova)
```

**Linear Model ratio across all years**
```{r linear model, message=FALSE, warning=FALSE, echo=FALSE}
fish_lm<-lm(data=fish_all, FINALVALUE ~ FINALWEIGHT) 

summary(fish_lm)
```

**MLR ratio across all years**
```{r multiple linear regression model, message=FALSE, warning=FALSE, echo=FALSE}
fish_multi_lm<-lm(data = fish_all, FINALVALUE ~ FINALWEIGHT + species_group)

summary(fish_multi_lm)
```




